openapi: 3.1.0
info:
  title: "ihavefood"
  description: "Only theses provinces can be used -> Chiang Mai, Bangkok, Phuket, Lampang, Rayong" 
  version: 0.1.0
servers:
    - url: "http://localhost:180"
      description: "abcdefg"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
      
paths:

#---------------Auth Service-----------------
  /auth/register:
    post:
      tags:
        - auth
      summary: Register a new user
      description: Register a new user 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                phone_number:
                  type: string
                address:
                  type: object
                  properties:
                    address_name:
                      type: string
                    sub_district:
                      type: string
                    district:
                      type: string
                    province:
                      type: string
                    postal_code:
                      type: string
            examples:
              example1:
                value: 
                  username: "yuki002"
                  email: "yuki_sleep@mail.com"
                  password: "secret"
                  phone_number: "081 222 3333"
                  address:
                    address_name: "Jai Dee Hotel"
                    sub_district: "Mueang"
                    district: "Chiang Mai"
                    province: "Chiang Mai"
                    postal_code: "50200"
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input

  /auth/login:
    get:
      tags:
        - auth
      summary: Logs user into the system
      description: "XXXXXXXXXXX"
      responses:
        '200':
          description: Successful login with access token and token expiration time (Unix)
      security:
        - basicAuth: []

  /auth/users/roles:
    put:
      tags:
        - auth
      summary: Assign role to User
      description: "0 Visitor, 1 User, 2 Admin"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  default: yuki002
                role:
                  type: integer
                  default: 2
      responses:
        '200':
          description: Successful login with access token and token expiration time (Unix)
      security:
        - bearerAuth: []

#---------------User Service-----------------
# TODO add more methods
  /api/users/{username}:
    get:
      tags: 
        - user
      summary: "Returns a user"
      description: "Returns a user from the system."
      parameters:
        - name: username
          in: path
          required: true
          description: "The username of the user to retrieve."
          schema:
            type: string
      responses:
        '200':
          description: ssss
      security:
        - bearerAuth: []
    delete:
      tags: 
        - user
      summary: "delete a user"
      parameters:
        - name: username
          in: path
          required: true
          description: "The username of the user to delete."
          schema:
            type: string
      responses:
        '200':
          description: ssss
      security:
        - bearerAuth: []

  /api/users:
    get:
      tags: 
        - user
      summary: "Returns a list of users"
      description: "Returns a list of users from the system."
      responses:
        '200':
          description: ssss
      security:
        - bearerAuth: []


#---------------Order Service-----------------
  /api/orders/place-order:
    post:
      tags:
      - order 
      summary: Place an order
      description: Endpoint to place an order at a restaurant.
      operationId: placeOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                restaurant_name:
                  type: string
                menus:
                  type: array
                  items:
                    type: object
                    properties:
                      food_name:
                        type: string
                      price:
                        type: number
                delivery_fee:
                  type: number
                coupon_code:
                  type: string
                coupon_discount:
                  type: number
                total:
                  type: number
                address:
                  type: object
                  properties:
                    address_name:
                      type: string
                    sub_district:
                      type: string
                    district:
                      type: string
                    province:
                      type: string
                    postalCode:
                      type: string
                    country:
                      type: string
                contact:
                  type: object
                  properties:
                    phone_number:
                      type: string
                payment_method:
                  type: integer
                  description: "0 = Cash, 1 = Credit Card"
            examples:
              asdasd:
                value:
                  username: "yuki002"
                  restaurant_name: "HaiDee"
                  menus:
                    - food_name: "Pad Thai"
                      price: 50
                  delivery_fee: 50
                  coupon_code: "129dh012"
                  coupon_discount: 20
                  total: 150
                  address:
                    address_name: "Home"
                    sub_district: "Nong Hoi"
                    district: "Mueang Chiang Mai"
                    province: "Chiang Mai"
                    postal_code: "50000"
                    country: "Thailand"
                  contact:
                    phone_number: "+668 1234 5678"
                  payment_method: 0
      responses:
        '200':
          description: Successfully placed an order
        '400':
          description: Invalid request
      security:
        - bearerAuth: [] 

  /api/orders/{username}:
    get:
      tags:
        - order
      summary: Get user order history
      description: Returns the order history for a specific user.
      parameters:
        - name: username
          in: path
          required: true
          description: The username whose orders are to be retrieved.
          schema:
            type: string
      responses:
        '200':
          description: List of orders for the user
        '404':
          description: User not found
      security:
        - bearerAuth: [] 

#---------------Delivery Service-----------------
  /api/deliveries/riders/accept:
    post:
      tags:
        - delivery
      summary: Accept an order
      description: Endpoint for a rider to accept an order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                rider_id:
                  type: string
                order_id:
                  type: string
            examples:
              ex:
                value: 
                  rider_id: "rider002"
                  order_id: "66af00af1687c32893d15693"
      responses:
        '200':
          description: Order accepted successfully
        '400':
          description: Invalid request
      security:
        - bearerAuth: [] 

#---------------Restaurant Service-----------------
  /api/restaurants/{restaurant_name}:
    get:
      tags:
        - restaurant
      summary: List menus of a restaurant
      description: Returns the menus of a specific restaurant.
      parameters:
        - name: restaurant_name
          in: path
          required: true
          description: The name of the restaurant.
          schema:
            type: string
      responses:
        '200':
          description: Menus of the restaurant
        '404':
          description: Restaurant not found
      security:
        - bearerAuth: [] 

  /api/restaurants:
    get:
      tags:
        - restaurant
      summary: List all restaurants
      description: Returns a list of all registered restaurants.
      responses:
        '200':
          description: List of all restaurants
      security:
        - bearerAuth: [] 
    post:
      tags:
        - restaurant
      summary: Register a new restaurant
      description: Register a new restaurant in the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant_name:
                  type: string
                menus:
                  type: array
                  items:
                    type: object
                    properties:
                      food_name:
                        type: string
                      price:
                        type: number
            examples:
              ex1:
                 value:
                  restaurant_name: "HaiDee"
                  menus:
                  - food_name: "Pad Thai"
                    price: 50
      responses:
        '201':
          description: Restaurant registered successfully
        '400':
          description: Invalid request
      security:
        - bearerAuth: [] 

  /api/restaurants/menus:
    post:
      tags:
        - restaurant
      summary: Add menu to restaurant
      description: Add a new menu item to a restaurant's menu.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant_name:
                  type: string
                menus:
                  type: array
                  items:
                    type: object
                    properties:
                      food_name:
                        type: string
                      price:
                        type: number
              restaurant_name: "HaiDee"
              menus:
                - food_name: "Pad Thai"
                  price: 50
              required:
                - restaurant_name
                - menus
      responses:
        '201':
          description: Menu added successfully
        '400':
          description: Invalid request
      security:
        - bearerAuth: [] 

#---------------Coupon Service-----------------
  /api/coupons:
    get:
      tags:
        - coupon
      summary: Get list of coupon details
      description: TODO
      responses:
        '200':
          description: Coupon details
      security:
        - bearerAuth: [] 
    post:
      tags:
        - coupon
      summary: Add Coupon ( for admin )
      description: TODO
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coupon_type:
                  type: integer
                  description: 0=UNSPECIFIED, 1=DISCOUNT, 2=FREE_DELIVERY
                discount:
                  type: integer
                expire_in_hour:
                  type: integer
                quantity:
                  type: integer
              required:
                - coupon_type
              allOf:
                - if:
                    properties:
                      coupon_type:
                        enum: [1]
                  then:
                    required:
                      - discount
                - if:
                    properties:
                      coupon_type:
                        enum: [2]
                  then:
                    not:
                      required: [discount]
      responses:
        '200':
          description: Coupon details
      security:
        - bearerAuth: [] 

  /api/coupons/{code}:
    get:
      tags:
        - coupon
      summary: Get coupon details
      description: Retrieve details of a specific coupon by code.
      parameters:
        - name: code
          in: path
          required: true
          description: The coupon code to retrieve.
          schema:
            type: string
      responses:
        '200':
          description: Coupon details
        '404':
          description: Coupon not found
      security:
        - bearerAuth: [] 
    put:
      tags:
        - coupon
      summary: Apply coupon
      description: TODO
      parameters:
        - name: code
          in: path
          required: true
          description: The coupon being used
          schema:
            type: string
      responses:
        '200':
          description: success
      security:
        - bearerAuth: [] 
#---------------END-----------------

